/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INFT__factory } from "./INFT__factory";
export { IOrganizationController__factory } from "./IOrganizationController__factory";
