/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomERC1155Burnable } from "./CustomERC1155Burnable";
export type { CustomERC1155Supply } from "./CustomERC1155Supply";
export type { CustomERC1155URIStorage } from "./CustomERC1155URIStorage";
