/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dealSol from "./Deal.sol";
export type { dealSol };
import type * as organizationSol from "./Organization.sol";
export type { organizationSol };
import type * as extensions from "./extensions";
export type { extensions };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CustomERC1155 } from "./CustomERC1155";
export type { Logger } from "./Logger";
export type { NFT } from "./NFT";
