/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomERC1155Burnable__factory } from "./CustomERC1155Burnable__factory";
export { CustomERC1155Supply__factory } from "./CustomERC1155Supply__factory";
export { CustomERC1155URIStorage__factory } from "./CustomERC1155URIStorage__factory";
